package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;



@Controller	// This means that this class is a Controller
@RequestMapping(path="/task") // This means URL's start with /demo (after Application path)
public class TaskController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private TaskRepository taskRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewTask (@RequestParam String task) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Task n = new Task();
		n.setTask(task);
		taskRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Task> getAllUsers() {
		return taskRepository.findAll();
	}
}
